insertPet:
    path: /insertPet
    controller: App\Infrastructure\Controller\PetController::insertPet
    methods: [POST]

updatePet:
    path: /updatePet
    controller: App\Infrastructure\Controller\PetController::updatePet
    methods: [POST]

listPetByKey:
    path: /listPetByKey/{key}/{value}
    controller: App\Infrastructure\Controller\PetController::listPetByKey

listPet:
    path: /listPet
    controller: App\Infrastructure\Controller\PetController::listPet

uploadImage:
    path: /uploadImage
    controller: App\Infrastructure\Controller\PetController::uploadImage
    methods: [POST]

