success:
    path: /success/{name}/{apellidos}
    controller: App\Infrastructure\Controller\UserController::success

insertUser:
    path: /insertUser
    controller: App\Infrastructure\Controller\UserController::insertUser

insertAddress:
    path: /insertAddress/{street}/{number}/{userId}/{floor}/{floorInformation}/{province}/{city}/{cp}
    controller: App\Infrastructure\Controller\AddressController::insertAddress
